default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: rubylover

development:
  <<: *default
  database: zq_production_dev
test:
  <<: *default
  database: zq_production_test
production:
  <<: *default
  adapter: postgresql
  # adapter: mysql2
  database: zq_production
  # database: adsapp_production_dev
  username: root
  password: 